version: "3.7"
services:
  telegraf-statsd:
    image: "telegraf:1.19.3"
    ports:
      - 8125:8125/udp
    volumes: 
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    entrypoint: telegraf
    command: 
      - -config
      - /etc/telegraf/telegraf.conf
